# !/usr/bin/python
# -*- coding: utf-8 -*-
import os

# Parent Directory where all Industry dirs are created and files are saved
BASE_LOCATION = os.path.dirname(os.path.dirname(__file__))

FILES_REPO = os.path.join(BASE_LOCATION, 'MISC_FILES')
# here we keep 'formatted' site files coming from gatekeeper
FILES_BASE_LOCATION = os.path.join(FILES_REPO, 'DATA_FILES')
# zipped metadata + site_file
ZIP_DIR = os.path.join(FILES_REPO, 'ZIP_DIR')
# keep files from database
CSV_FROM_DB = os.path.join(FILES_REPO, 'FILES_FROM_DB')
# path for metadata.csv
METADATA_FILE = os.path.join(FILES_REPO, 'metadata.csv')
# path for stations.csv and industries.csv
STATIONS_CACHE = os.path.join(CSV_FROM_DB, 'stations.csv')
INDUSTRIES_CACHE = os.path.join(CSV_FROM_DB, 'industries.csv')

# Temp folder
TEMP_DIR = os.path.join(FILES_REPO, 'TEMP_DIR')
# pass all directories which needs to be created
AAXIPRO_DIRS = [FILES_BASE_LOCATION, ZIP_DIR, CSV_FROM_DB, TEMP_DIR]

###################################Madhya Pradesh##############################
MPPCB_REALTIME = 'http://esc.mp.gov.in/MPPCBServer/realtimeUpload'
MPPCB_DELAYED = 'http://esc.mp.gov.in/MPPCBServer/DelayedUpload'

###################################Mumbai###################################
MPCB_REALTIME = 'http://onlinecems.ecmpcb.in/mpcb/realtimeUpload'
MPCB_DELAYED = 'http://onlinecems.ecmpcb.in/mpcb/delayedUpload'

###################################KERELA###################################
KSPCB_REALTIME = 'http://keralapcb.glensserver.com/KSPCBGLensServer/realTimeUpload'
KSPCB_DELAYED = 'http://keralapcb.glensserver.com/KSPCBGLensServer/delayedUpload'

###################################CPCB###################################
# TODO: check this
CPCB_REALTIME = 'http://cpcbrtdms.nic.in/v1.0/industry/{industry_id}/data'
CPCB_DELAYED = 'http://cpcbrtdms.nic.in/v1.0/industry/{industry_id}/data'

###################################OSPCB###################################
OSPCB_REALTIME = 'http://117.239.117.27:9091/OSPCBserver/realTimeUpload'
OSPCB_DELAYED = 'http://117.239.117.27:9091/OSPCBserver/delayedUpload'

###################################UKPC###################################
UKPCB_REALTIME = 'http://gangatarang.ilens.io/GangaTarang/LiveData'
UKPCB_DELAYED = 'http://onlinecems.ecmpcb.in/mpcb/delayedUpload'

###################################DPCC###################################
DPCC_REALTIME = 'http://173.208.244.178/dlcpcb'

URLS = [MPCB_REALTIME,
        MPCB_DELAYED,
        KSPCB_REALTIME,
        KSPCB_DELAYED,
        CPCB_REALTIME,
        CPCB_DELAYED,
        OSPCB_REALTIME,
        OSPCB_DELAYED,
        UKPCB_REALTIME,
        UKPCB_DELAYED,
        DPCC_REALTIME,
        MPPCB_REALTIME,
        MPPCB_DELAYED]

UPLOAD_TYPE_CHOICES = (
    ('realtime', 'Realtime'),
    ('delayed', 'Delayed')
)
PERMISSIONS = (
    ('view_site', 'View Site'),
    ('download_report', 'Download Report'),
    ('manage_site', 'Site Management'),
    ('upload_data', 'Upload Data to PCB'),
    ('view_upload_details', 'View Upload Details'),
    ('view_graph', 'View Graph'),
    ('client_management', 'Client Management'),
)
USER_CHOICES = (
    ('CUSTOMER', 'Customer'),
    ('CPCB', 'CPCB'),
    ('ADMIN', 'Super Admin'),
    ('STAFF', 'Staff User'),
)
# PCB_CHOICES = (
#     (None, '-Select Type-'),
#
#
#     ('BSPCB', 'BSPCB'),
#     ('CPCB', 'CPCB'), ('DJB', 'DJB'), ('HSPCB', 'HSPCB'), ('KSPCB', 'KSPCB'),
#     ('MPCB', 'MPCB'), ('MPPCB', 'MPPCB'), ('OSPCB', 'OSPCB'), ('PPCB', 'PPCB'),
#     ('RSPCB', 'RSPCB'), ('WBPCB', 'WBPCB'), ('UKPCB', 'UKPCB'),
#     ('DPCC', 'DPCC'), ('JSPCB', 'JSPCB'),
#     # add PCBs above below remains fix
#     ('CETP', 'CETP'), ('ADMIN', 'ADMIN'), ('DEMO', 'DEMO'),
# )
PCB_CHOICES = (
    (None, '-Select Type-'),
    ('BSPCB', 'BSPCB'),
    ('CETP', 'CETP'),
    ('CPCB', 'CPCB'),
    ('DJB', 'DJB'),
    ('DPCC', 'DPCC'),
    ('GPCB', 'GPCB'),
    ('HSPCB', 'HSPCB'),
    ('JSPCB', 'JSPCB'),
    ('KSPCB', 'KSPCB'),
    ('MPCB', 'MPCB'),
    ('MPPCB', 'MPPCB'),
    ('OSPCB', 'OSPCB'),
    ('PPCB', 'PPCB'),
    ('RSPCB', 'RSPCB'),
    ('SikkimPCB', 'SikkimPCB'),
    ('UKPCB', 'UKPCB'),
    ('UPPCB', 'UPPCB'),
    ('WBPCB', 'WBPCB'),
    ('DEMO', 'DEMO'),
    ('ADMIN', 'ADMIN')
)
CATEGORIES = (
    ('Aluminium', 'Aluminium'),
    ('Beverages', 'Beverages'),
    ('Cement', 'Cement'),
    ('CETP', 'CETP'),
    ('Chemical & Pharmaceutical', 'Chemical & Pharmaceutical'),
    ('ChlorAlkali', 'ChlorAlkali'),
    ('Copper', 'Copper'),
    ('Dairy', 'Dairy'),
    ('Distillery', 'Distillery'),
    ('Dye & Dye Intermediates', 'Dye & Dye Intermediates'),
    ('Fertilizer', 'Fertilizer'),
    ('Iron & Steel', 'Iron & Steel'),
    ('Oil Refinery', 'Oil Refinery'),
    ('Pesticide', 'Pesticide'),
    ('Petrochemical', 'Petrochemical'),
    ('Pharmaceuticals', 'Pharmaceuticals'),
    ('Power Plant', 'Power Plant'),
    ('Pulp & Paper', 'Pulp & Paper'),
    ('Slaughter House', 'Slaughter House'),
    ('Sugar', 'Sugar'),
    ('Tannery', 'Tannery'),
    ('Textile', 'Textile'),
    ('Zinc', 'Zinc'),
    ('Chemical', 'Chemical'),
    ('STP', 'STP'),
    ('Coal and Mines', 'Coal and Mines'),
    ('Polymer', 'Polymer'),
    ('Food & Beverages', 'Food & Beverages'),
    ('Food Dairy & Beverages', 'Food Dairy & Beverages'),
    ('Automoblie', 'Automoblie'),
    ('Common Bio Medical Waste Treatment Plant',
     'Common Bio Medical Waste Treatment Plant'),
    ('Engineering', 'Engineering'),
    ('Other', 'Other'),
)

CITIES = ((None, '-Select City-'),
          ('Achhnera', 'Achhnera'),
          ('Adalaj', 'Adalaj'),
          ('Adilabad', 'Adilabad'),
          ('Adoni', 'Adoni'),
          ('Adoor', 'Adoor'),
          ('Adra', 'Adra'),
          ('Adyar', 'Adyar'),
          ('Afzalpur', 'Afzalpur'),
          ('Agartala', 'Agartala'),
          ('Agra', 'Agra'),
          ('Ahmedabad', 'Ahmedabad'),
          ('Aizawl', 'Aizawl'),
          ('Ajmer', 'Ajmer'),
          ('Alappuzha', 'Alappuzha'),
          ('Aligarh', 'Aligarh'),
          ('Alipur', 'Alipur'),
          ('Allahabad', 'Allahabad'),
          ('Alwar', 'Alwar'),
          ('Amalapuram', 'Amalapuram'),
          ('Ambikapur', 'Ambikapur'),
          ('Amreli', 'Amreli'),
          ('Amritsar', 'Amritsar'),
          ('Amroha', 'Amroha'),
          ('Anakapalle', 'Anakapalle'),
          ('Anand', 'Anand'),
          ('Anantapur', 'Anantapur'),
          ('Anjar', 'Anjar'),
          ('Ankleshwar', 'Ankleshwar'),
          ('Arakkonam', 'Arakkonam'),
          ('Arambagh', 'Arambagh'),
          ('Araria', 'Araria'),
          ('Arrah', 'Arrah'),
          ('Arsikere', 'Arsikere'),
          ('Aruppukkottai', 'Aruppukkottai'),
          ('Arwal', 'Arwal'),
          ('Asansol', 'Asansol'),
          ('Asarganj', 'Asarganj'),
          ('Athni', 'Athni'),
          ('Attingal', 'Attingal'),
          ('Aurangabad', 'Aurangabad'),
          ('Azamgarh', 'Azamgarh'),
          ('Bagaha', 'Bagaha'),
          ('Bageshwar', 'Bageshwar'),
          ('Bahadurgarh', 'Bahadurgarh'),
          ('Baharampur', 'Baharampur'),
          ('Bahraich', 'Bahraich'),
          ('Balangir', 'Balangir'),
          ('Baleshwar Town', 'Baleshwar Town'),
          ('Ballari', 'Ballari'),
          ('Balurghat', 'Balurghat'),
          ('Bankura', 'Bankura'),
          ('Bapatla', 'Bapatla'),
          ('Barbil', 'Barbil'),
          ('Bargarh', 'Bargarh'),
          ('Barh', 'Barh'),
          ('Baripada Town', 'Baripada Town'),
          ('Barmer', 'Barmer'),
          ('Barnala', 'Barnala'),
          ('Barpeta', 'Barpeta'),
          ('Batala', 'Batala'),
          ('Bathinda', 'Bathinda'),
          ('Begusarai', 'Begusarai'),
          ('Belagavi', 'Belagavi'),
          ('Bellampalle', 'Bellampalle'),
          ('Belonia', 'Belonia'),
          ('Bengaluru', 'Bengaluru'),
          ('Bettiah', 'Bettiah'),
          ('BhabUrban Agglomeration', 'BhabUrban Agglomeration'),
          ('Bhadrachalam', 'Bhadrachalam'),
          ('Bhadrak', 'Bhadrak'),
          ('Bhagalpur', 'Bhagalpur'),
          ('Bhainsa', 'Bhainsa'),
          ('Bharatpur', 'Bharatpur'),
          ('Bharuch', 'Bharuch'),
          ('Bhatapara', 'Bhatapara'),
          ('Bhavnagar', 'Bhavnagar'),
          ('Bhawanipatna', 'Bhawanipatna'),
          ('Bheemunipatnam', 'Bheemunipatnam'),
          ('Bhilai Nagar', 'Bhilai Nagar'),
          ('Bhilwara', 'Bhilwara'),
          ('Bhimavaram', 'Bhimavaram'),
          ('Bhiwani', 'Bhiwani'),
          ('Bhongir', 'Bhongir'),
          ('Bhubaneswar', 'Bhubaneswar'),
          ('Bhuj', 'Bhuj'),
          ('Bikaner', 'Bikaner'),
          ('Bilaspur', 'Bilaspur'),
          ('Bobbili', 'Bobbili'),
          ('Bodhan', 'Bodhan'),
          ('Bongaigaon City', 'Bongaigaon City'),
          ('Brahmapur', 'Brahmapur'),
          ('Buxar', 'Buxar'),
          ('Byasanagar', 'Byasanagar'),
          ('Chalakudy', 'Chalakudy'),
          ('Chandausi', 'Chandausi'),
          ('Chandigarh', 'Chandigarh'),
          ('Changanassery', 'Changanassery'),
          ('Charkhi Dadri', 'Charkhi Dadri'),
          ('Chennai', 'Chennai'),
          ('Cherthala', 'Cherthala'),
          ('Chhapra', 'Chhapra'),
          ('Chhapra', 'Chhapra'),
          ('Chikkamagaluru', 'Chikkamagaluru'),
          ('Chilakaluripet', 'Chilakaluripet'),
          ('Chirala', 'Chirala'),
          ('Chirmiri', 'Chirmiri'),
          ('Chittoor', 'Chittoor'),
          ('Chittur-Thathamangalam', 'Chittur-Thathamangalam'),
          ('Coimbatore', 'Coimbatore'),
          ('Cuttack', 'Cuttack'),
          ('Dalli-Rajhara', 'Dalli-Rajhara'),
          ('Darbhanga', 'Darbhanga'),
          ('Darjiling', 'Darjiling'),
          ('Davanagere', 'Davanagere'),
          ('Deesa', 'Deesa'),
          ('Dehradun', 'Dehradun'),
          ('Dehri-on-Sone', 'Dehri-on-Sone'),
          ('Delhi', 'Delhi'),
          ('Dhamtari', 'Dhamtari'),
          ('Dharmanagar', 'Dharmanagar'),
          ('Dharmavaram', 'Dharmavaram'),
          ('Dhenkanal', 'Dhenkanal'),
          ('Dhoraji', 'Dhoraji'),
          ('Dhubri', 'Dhubri'),
          ('Dhuri', 'Dhuri'),
          ('Dibrugarh', 'Dibrugarh'),
          ('Dimapur', 'Dimapur'),
          ('Diphu', 'Diphu'),
          ('Dumraon', 'Dumraon'),
          ('Durg', 'Durg'),
          ('Eluru', 'Eluru'),
          ('English Bazar', 'English Bazar'),
          ('Erode', 'Erode'),
          ('Etawah', 'Etawah'),
          ('Faridabad', 'Faridabad'),
          ('Faridkot', 'Faridkot'),
          ('Farooqnagar', 'Farooqnagar'),
          ('Fatehabad', 'Fatehabad'),
          ('Fatehpur Sikri', 'Fatehpur Sikri'),
          ('Fazilka', 'Fazilka'),
          ('Firozabad', 'Firozabad'),
          ('Firozpur', 'Firozpur'),
          ('Firozpur Cantt.', 'Firozpur Cantt.'),
          ('Forbesganj', 'Forbesganj'),
          ('Gadwal', 'Gadwal'),
          ('Gangarampur', 'Gangarampur'),
          ('Gaya', 'Gaya'),
          ('Ghaziabad', 'Ghaziabad'),
          ('Goalpara', 'Goalpara'),
          ('Gobichettipalayam', 'Gobichettipalayam'),
          ('Gobindgarh', 'Gobindgarh'),
          ('Godhra', 'Godhra'),
          ('Gohana', 'Gohana'),
          ('Gokak', 'Gokak'),
          ('Gooty', 'Gooty'),
          ('Gopalganj', 'Gopalganj'),
          ('Gudivada', 'Gudivada'),
          ('Gudur', 'Gudur'),
          ('Guntakal', 'Guntakal'),
          ('Guntur', 'Guntur'),
          ('Gurdaspur', 'Gurdaspur'),
          ('Gurgaon', 'Gurgaon'),
          ('Guruvayoor', 'Guruvayoor'),
          ('Guwahati', 'Guwahati'),
          ('Habra', 'Habra'),
          ('Hajipur', 'Hajipur'),
          ('Haldwani-cum-Kathgodam', 'Haldwani-cum-Kathgodam'),
          ('Hansi', 'Hansi'),
          ('Hapur', 'Hapur'),
          ('Hardoi', 'Hardoi'),
          ('Hardwar', 'Hardwar'),
          ('Hindupur', 'Hindupur'),
          ('Hisar', 'Hisar'),
          ('Hoshiarpur', 'Hoshiarpur'),
          ('Hubli-Dharwad', 'Hubli-Dharwad'),
          ('Hugli-Chinsurah', 'Hugli-Chinsurah'),
          ('Hyderabad', 'Hyderabad'),
          ('Imphal', 'Imphal'),
          ('Jagdalpur', 'Jagdalpur'),
          ('Jaggaiahpet', 'Jaggaiahpet'),
          ('Jagraon', 'Jagraon'),
          ('Jagtial', 'Jagtial'),
          ('Jaipur', 'Jaipur'),
          ('Jalandhar', 'Jalandhar'),
          ('Jalandhar Cantt.', 'Jalandhar Cantt.'),
          ('Jalpaiguri', 'Jalpaiguri'),
          ('Jamalpur', 'Jamalpur'),
          ('Jammalamadugu', 'Jammalamadugu'),
          ('Jamnagar', 'Jamnagar'),
          ('Jamui', 'Jamui'),
          ('Jangaon', 'Jangaon'),
          ('Jatani', 'Jatani'),
          ('Jehanabad', 'Jehanabad'),
          ('Jhansi', 'Jhansi'),
          ('Jhargram', 'Jhargram'),
          ('Jharsuguda', 'Jharsuguda'),
          ('Jind', 'Jind'),
          ('Jodhpur', 'Jodhpur'),
          ('Jorhat', 'Jorhat'),
          ('Kadapa', 'Kadapa'),
          ('Kadi', 'Kadi'),
          ('Kadiri', 'Kadiri'),
          ('Kagaznagar', 'Kagaznagar'),
          ('Kailasahar', 'Kailasahar'),
          ('Kaithal', 'Kaithal'),
          ('Kakinada', 'Kakinada'),
          ('Kalimpong', 'Kalimpong'),
          ('Kalpi', 'Kalpi'),
          ('Kamareddy', 'Kamareddy'),
          ('Kancheepuram', 'Kancheepuram'),
          ('Kandukur', 'Kandukur'),
          ('Kanhangad', 'Kanhangad'),
          ('Kannur', 'Kannur'),
          ('Kanpur', 'Kanpur'),
          ('Kapadvanj', 'Kapadvanj'),
          ('Kapurthala', 'Kapurthala'),
          ('Karaikal', 'Karaikal'),
          ('Karimganj', 'Karimganj'),
          ('Karimnagar', 'Karimnagar'),
          ('Karnal', 'Karnal'),
          ('Karur', 'Karur'),
          ('Karwar', 'Karwar'),
          ('Kasaragod', 'Kasaragod'),
          ('Kashipur', 'Kashipur'),
          ('Katihar', 'Katihar'),
          ('Kavali', 'Kavali'),
          ('Kayamkulam', 'Kayamkulam'),
          ('Kendrapara', 'Kendrapara'),
          ('Kendujhar', 'Kendujhar'),
          ('Keshod', 'Keshod'),
          ('Khair', 'Khair'),
          ('Khambhat', 'Khambhat'),
          ('Khammam', 'Khammam'),
          ('Khanna', 'Khanna'),
          ('Kharagpur', 'Kharagpur'),
          ('Kharar', 'Kharar'),
          ('Khowai', 'Khowai'),
          ('Kishanganj', 'Kishanganj'),
          ('Kochi', 'Kochi'),
          ('Kodungallur', 'Kodungallur'),
          ('Kohima', 'Kohima'),
          ('Kolar', 'Kolar'),
          ('Kolkata', 'Kolkata'),
          ('Kollam', 'Kollam'),
          ('Koratla', 'Koratla'),
          ('Korba', 'Korba'),
          ('Kot Kapura', 'Kot Kapura'),
          ('Kothagudem', 'Kothagudem'),
          ('Kottayam', 'Kottayam'),
          ('Kovvur', 'Kovvur'),
          ('Koyilandy', 'Koyilandy'),
          ('Kozhikode', 'Kozhikode'),
          ('Kunnamkulam', 'Kunnamkulam'),
          ('Kurnool', 'Kurnool'),
          ('Kyathampalle', 'Kyathampalle'),
          ('Lachhmangarh', 'Lachhmangarh'),
          ('Ladnu', 'Ladnu'),
          ('Ladwa', 'Ladwa'),
          ('Laharpur', 'Laharpur'),
          ('Lakheri', 'Lakheri'),
          ('Lakhimpur', 'Lakhimpur'),
          ('Lakhisarai', 'Lakhisarai'),
          ('Lakshmeshwar', 'Lakshmeshwar'),
          ('Lal Gopalganj Nindaura', 'Lal Gopalganj Nindaura'),
          ('Lalganj', 'Lalganj'),
          ('Lalganj', 'Lalganj'),
          ('Lalgudi', 'Lalgudi'),
          ('Lalitpur', 'Lalitpur'),
          ('Lalsot', 'Lalsot'),
          ('Lanka', 'Lanka'),
          ('Lar', 'Lar'),
          ('Lathi', 'Lathi'),
          ('Lilong', 'Lilong'),
          ('Limbdi', 'Limbdi'),
          ('Lingsugur', 'Lingsugur'),
          ('Longowal', 'Longowal'),
          ('Loni', 'Loni'),
          ('Losal', 'Losal'),
          ('Lucknow', 'Lucknow'),
          ('Ludhiana', 'Ludhiana'),
          ('Lumding', 'Lumding'),
          ('Lunawada', 'Lunawada'),
          ('Lunglei', 'Lunglei'),
          ('Macherla', 'Macherla'),
          ('Machilipatnam', 'Machilipatnam'),
          ('Madanapalle', 'Madanapalle'),
          ('Maddur', 'Maddur'),
          ('Madhepura', 'Madhepura'),
          ('Madhubani', 'Madhubani'),
          ('Madhugiri', 'Madhugiri'),
          ('Madikeri', 'Madikeri'),
          ('Madurai', 'Madurai'),
          ('Magadi', 'Magadi'),
          ('Mahalingapura', 'Mahalingapura'),
          ('Maharajganj', 'Maharajganj'),
          ('Mahasamund', 'Mahasamund'),
          ('Mahbubnagar', 'Mahbubnagar'),
          ('Mahe', 'Mahe'),
          ('Mahemdabad', 'Mahemdabad'),
          ('Mahendragarh', 'Mahendragarh'),
          ('Mahesana', 'Mahesana'),
          ('Mahnar Bazar', 'Mahnar Bazar'),
          ('Mahuva', 'Mahuva'),
          ('Mainaguri', 'Mainaguri'),
          ('Makhdumpur', 'Makhdumpur'),
          ('Makrana', 'Makrana'),
          ('Malappuram', 'Malappuram'),
          ('Malavalli', 'Malavalli'),
          ('Malda', 'Malda'),
          ('Malerkotla', 'Malerkotla'),
          ('Malkangiri', 'Malkangiri'),
          ('Malout', 'Malout'),
          ('Malpura', 'Malpura'),
          ('Malur', 'Malur'),
          ('Manachanallur', 'Manachanallur'),
          ('Manavadar', 'Manavadar'),
          ('Mancherial', 'Mancherial'),
          ('Mandalgarh', 'Mandalgarh'),
          ('Mandamarri', 'Mandamarri'),
          ('Mandapeta', 'Mandapeta'),
          ('Mandawa', 'Mandawa'),
          ('Mandi', 'Mandi'),
          ('Mandi Dabwali', 'Mandi Dabwali'),
          ('Mandvi', 'Mandvi'),
          ('Mandya', 'Mandya'),
          ('Manendragarh', 'Manendragarh'),
          ('Maner', 'Maner'),
          ('Mangaldoi', 'Mangaldoi'),
          ('Mangaluru', 'Mangaluru'),
          ('Manglaur', 'Manglaur'),
          ('Mangrol', 'Mangrol'),
          ('Mangrol', 'Mangrol'),
          ('Manihari', 'Manihari'),
          ('Mankachar', 'Mankachar'),
          ('Mansa', 'Mansa'),
          ('Mansa', 'Mansa'),
          ('Manuguru', 'Manuguru'),
          ('Manvi', 'Manvi'),
          ('Mapusa', 'Mapusa'),
          ('Margao', 'Margao'),
          ('Margherita', 'Margherita'),
          ('Marhaura', 'Marhaura'),
          ('Mariani', 'Mariani'),
          ('Marigaon', 'Marigaon'),
          ('Markapur', 'Markapur'),
          ('Marmagao', 'Marmagao'),
          ('Masaurhi', 'Masaurhi'),
          ('Mathabhanga', 'Mathabhanga'),
          ('Mathura', 'Mathura'),
          ('Mattannur', 'Mattannur'),
          ('Mavelikkara', 'Mavelikkara'),
          ('Mavoor', 'Mavoor'),
          ('Mayang Imphal', 'Mayang Imphal'),
          ('Medak', 'Medak'),
          ('Medinipur', 'Medinipur'),
          ('Meerut', 'Meerut'),
          ('Memari', 'Memari'),
          ('Merta City', 'Merta City'),
          ('Mirganj', 'Mirganj'),
          ('Miryalaguda', 'Miryalaguda'),
          ('Modasa', 'Modasa'),
          ('Modinagar', 'Modinagar'),
          ('Moga', 'Moga'),
          ('Mohali', 'Mohali'),
          ('Mokameh', 'Mokameh'),
          ('Mokokchung', 'Mokokchung'),
          ('Monoharpur', 'Monoharpur'),
          ('Moradabad', 'Moradabad'),
          ('Morvi', 'Morvi'),
          ('Motihari', 'Motihari'),
          ('Motipur', 'Motipur'),
          ('Mount Abu', 'Mount Abu'),
          ('Mudabidri', 'Mudabidri'),
          ('Mudalagi', 'Mudalagi'),
          ('Muddebihal', 'Muddebihal'),
          ('Mudhol', 'Mudhol'),
          ('Mukerian', 'Mukerian'),
          ('Muktsar', 'Muktsar'),
          ('Mulbagal', 'Mulbagal'),
          ('Mundargi', 'Mundargi'),
          ('Mungeli', 'Mungeli'),
          ('Munger', 'Munger'),
          ('Murliganj', 'Murliganj'),
          ('Murshidabad', 'Murshidabad'),
          ('Mussoorie', 'Mussoorie'),
          ('Muvattupuzha', 'Muvattupuzha'),
          ('Muzaffarpur', 'Muzaffarpur'),
          ('Nabadwip', 'Nabadwip'),
          ('Nabarangapur', 'Nabarangapur'),
          ('Nabha', 'Nabha'),
          ('Nadbai', 'Nadbai'),
          ('Nadiad', 'Nadiad'),
          ('Nagaon', 'Nagaon'),
          ('Nagapattinam', 'Nagapattinam'),
          ('Nagar', 'Nagar'),
          ('Nagari', 'Nagari'),
          ('Nagarkurnool', 'Nagarkurnool'),
          ('Nagaur', 'Nagaur'),
          ('Nagercoil', 'Nagercoil'),
          ('Nagina', 'Nagina'),
          ('Nagla', 'Nagla'),
          ('Nahan', 'Nahan'),
          ('Naharlagun', 'Naharlagun'),
          ('Naidupet', 'Naidupet'),
          ('Naihati', 'Naihati'),
          ('Naila Janjgir', 'Naila Janjgir'),
          ('Nainital', 'Nainital'),
          ('Najibabad', 'Najibabad'),
          ('Nakodar', 'Nakodar'),
          ('Nakur', 'Nakur'),
          ('Nalbari', 'Nalbari'),
          ('Namagiripettai', 'Namagiripettai'),
          ('Namakkal', 'Namakkal'),
          ('Nandivaram-Guduvancheri', 'Nandivaram-Guduvancheri'),
          ('Nandyal', 'Nandyal'),
          ('Nangal', 'Nangal'),
          ('Nanjangud', 'Nanjangud'),
          ('Nanjikottai', 'Nanjikottai'),
          ('Nanpara', 'Nanpara'),
          ('Narasapuram', 'Narasapuram'),
          ('Narasaraopet', 'Narasaraopet'),
          ('Naraura', 'Naraura'),
          ('Narayanpet', 'Narayanpet'),
          ('Nargund', 'Nargund'),
          ('Narkatiaganj', 'Narkatiaganj'),
          ('Narnaul', 'Narnaul'),
          ('Narsipatnam', 'Narsipatnam'),
          ('Narwana', 'Narwana'),
          ('Nasirabad', 'Nasirabad'),
          ('Natham', 'Natham'),
          ('Nathdwara', 'Nathdwara'),
          ('Naugachhia', 'Naugachhia'),
          ('Naugawan Sadat', 'Naugawan Sadat'),
          ('Nautanwa', 'Nautanwa'),
          ('Navalgund', 'Navalgund'),
          ('Navsari', 'Navsari'),
          ('Nawabganj', 'Nawabganj'),
          ('Nawada', 'Nawada'),
          ('Nawanshahr', 'Nawanshahr'),
          ('Nedumangad', 'Nedumangad'),
          ('Neem-Ka-Thana', 'Neem-Ka-Thana'),
          ('Nehtaur', 'Nehtaur'),
          ('Nelamangala', 'Nelamangala'),
          ('Nellikuppam', 'Nellikuppam'),
          ('Nellore', 'Nellore'),
          ('New Delhi', 'New Delhi'),
          ('Neyveli (TS)', 'Neyveli (TS)'),
          ('Neyyattinkara', 'Neyyattinkara'),
          ('Nidadavole', 'Nidadavole'),
          ('Nilambur', 'Nilambur'),
          ('Nimbahera', 'Nimbahera'),
          ('Nirmal', 'Nirmal'),
          ('Niwai', 'Niwai'),
          ('Nizamabad', 'Nizamabad'),
          ('Nohar', 'Nohar'),
          ('Noida', 'Noida'),
          ('Nokha', 'Nokha'),
          ('Nongstoin', 'Nongstoin'),
          ('Noorpur', 'Noorpur'),
          ('North Lakhimpur', 'North Lakhimpur'),
          ('Nuzvid', 'Nuzvid'),
          ('O Valley', 'O Valley'),
          ('Obra', 'Obra'),
          ('Oddanchatram', 'Oddanchatram'),
          ('Ongole', 'Ongole'),
          ('Orai', 'Orai'),
          ('Ottappalam', 'Ottappalam'),
          ('P.N.Patti', 'P.N.Patti'),
          ('Pacode', 'Pacode'),
          ('Padmanabhapuram', 'Padmanabhapuram'),
          ('Padra', 'Padra'),
          ('Padrauna', 'Padrauna'),
          ('Palacole', 'Palacole'),
          ('Palai', 'Palai'),
          ('Palakkad', 'Palakkad'),
          ('Palampur', 'Palampur'),
          ('Palani', 'Palani'),
          ('Palanpur', 'Palanpur'),
          ('Palasa Kasibugga', 'Palasa Kasibugga'),
          ('Pali', 'Pali'),
          ('Palia Kalan', 'Palia Kalan'),
          ('Palitana', 'Palitana'),
          ('Palladam', 'Palladam'),
          ('Pallapatti', 'Pallapatti'),
          ('Pallikonda', 'Pallikonda'),
          ('Palwal', 'Palwal'),
          ('Palwancha', 'Palwancha'),
          ('Panagudi', 'Panagudi'),
          ('Panaji', 'Panaji'),
          ('Panamattom', 'Panamattom'),
          ('Panchkula', 'Panchkula'),
          ('Panchla', 'Panchla'),
          ('PandUrban Agglomeration', 'PandUrban Agglomeration'),
          ('Panipat', 'Panipat'),
          ('Panniyannur', 'Panniyannur'),
          ('Panruti', 'Panruti'),
          ('Pappinisseri', 'Pappinisseri'),
          ('Paradip', 'Paradip'),
          ('Paramakudi', 'Paramakudi'),
          ('Parangipettai', 'Parangipettai'),
          ('Parasi', 'Parasi'),
          ('Paravoor', 'Paravoor'),
          ('Pardi', 'Pardi'),
          ('Parlakhemundi', 'Parlakhemundi'),
          ('Parvathipuram', 'Parvathipuram'),
          ('Paschim Punropara', 'Paschim Punropara'),
          ('Pasighat', 'Pasighat'),
          ('Patan', 'Patan'),
          ('Pathanamthitta', 'Pathanamthitta'),
          ('Pathankot', 'Pathankot'),
          ('Patiala', 'Patiala'),
          ('Patna', 'Patna'),
          ('Pattamundai', 'Pattamundai'),
          ('Patti', 'Patti'),
          ('Pattran', 'Pattran'),
          ('Pattukkottai', 'Pattukkottai'),
          ('Pauri', 'Pauri'),
          ('Pavagada', 'Pavagada'),
          ('Pedana', 'Pedana'),
          ('Peddapuram', 'Peddapuram'),
          ('Pehowa', 'Pehowa'),
          ('Perambalur', 'Perambalur'),
          ('Peravurani', 'Peravurani'),
          ('Peringathur', 'Peringathur'),
          ('Perinthalmanna', 'Perinthalmanna'),
          ('Periyakulam', 'Periyakulam'),
          ('Periyasemur', 'Periyasemur'),
          ('Pernampattu', 'Pernampattu'),
          ('Perumbavoor', 'Perumbavoor'),
          ('Petlad', 'Petlad'),
          ('Phagwara', 'Phagwara'),
          ('Phalodi', 'Phalodi'),
          ('Phillaur', 'Phillaur'),
          ('Phulabani', 'Phulabani'),
          ('Phulera', 'Phulera'),
          ('Phulpur', 'Phulpur'),
          ('Pihani', 'Pihani'),
          ('Pilani', 'Pilani'),
          ('Pilibanga', 'Pilibanga'),
          ('Pilibhit', 'Pilibhit'),
          ('Pilkhuwa', 'Pilkhuwa'),
          ('Pindwara', 'Pindwara'),
          ('Pinjore', 'Pinjore'),
          ('Pipar City', 'Pipar City'),
          ('Piriyapatna', 'Piriyapatna'),
          ('Piro', 'Piro'),
          ('Pithapuram', 'Pithapuram'),
          ('Pithoragarh', 'Pithoragarh'),
          ('Pollachi', 'Pollachi'),
          ('Polur', 'Polur'),
          ('Pondicherry', 'Pondicherry'),
          ('Ponnani', 'Ponnani'),
          ('Ponneri', 'Ponneri'),
          ('Ponnur', 'Ponnur'),
          ('Porbandar', 'Porbandar'),
          ('Powayan', 'Powayan'),
          ('Prantij', 'Prantij'),
          ('Pratapgarh', 'Pratapgarh'),
          ('Pratapgarh', 'Pratapgarh'),
          ('Proddatur', 'Proddatur'),
          ('Pudukkottai', 'Pudukkottai'),
          ('Pudupattinam', 'Pudupattinam'),
          ('Pukhrayan', 'Pukhrayan'),
          ('Puliyankudi', 'Puliyankudi'),
          ('Punalur', 'Punalur'),
          ('Punganur', 'Punganur'),
          ('Punjaipugalur', 'Punjaipugalur'),
          ('Puranpur', 'Puranpur'),
          ('Puri', 'Puri'),
          ('Purnia', 'Purnia'),
          ('PurqUrban Agglomerationzi', 'PurqUrban Agglomerationzi'),
          ('Purulia', 'Purulia'),
          ('Purwa', 'Purwa'),
          ('Puthuppally', 'Puthuppally'),
          ('Puttur', 'Puttur'),
          ('Puttur', 'Puttur'),
          ('Qadian', 'Qadian'),
          ('Raayachuru', 'Raayachuru'),
          ('Rabkavi Banhatti', 'Rabkavi Banhatti'),
          ('Radhanpur', 'Radhanpur'),
          ('Rae Bareli', 'Rae Bareli'),
          ('Rafiganj', 'Rafiganj'),
          ('Raghunathganj', 'Raghunathganj'),
          ('Raghunathpur', 'Raghunathpur'),
          ('Raiganj', 'Raiganj'),
          ('Raigarh', 'Raigarh'),
          ('Raikot', 'Raikot'),
          ('Raipur', 'Raipur'),
          ('Rairangpur', 'Rairangpur'),
          ('Raisinghnagar', 'Raisinghnagar'),
          ('Rajagangapur', 'Rajagangapur'),
          ('Rajahmundry', 'Rajahmundry'),
          ('Rajakhera', 'Rajakhera'),
          ('Rajaldesar', 'Rajaldesar'),
          ('Rajam', 'Rajam'),
          ('Rajampet', 'Rajampet'),
          ('Rajapalayam', 'Rajapalayam'),
          ('Rajgarh (Alwar)', 'Rajgarh (Alwar)'),
          ('Rajgarh (Churu)', 'Rajgarh (Churu)'),
          ('Rajgir', 'Rajgir'),
          ('Rajkot', 'Rajkot'),
          ('Rajnandgaon', 'Rajnandgaon'),
          ('Rajpipla', 'Rajpipla'),
          ('Rajpura', 'Rajpura'),
          ('Rajsamand', 'Rajsamand'),
          ('Rajula', 'Rajula'),
          ('Ramachandrapuram', 'Ramachandrapuram'),
          ('Ramagundam', 'Ramagundam'),
          ('Ramanagaram', 'Ramanagaram'),
          ('Ramanathapuram', 'Ramanathapuram'),
          ('Ramdurg', 'Ramdurg'),
          ('Rameshwaram', 'Rameshwaram'),
          ('Ramganj Mandi', 'Ramganj Mandi'),
          ('Ramnagar', 'Ramnagar'),
          ('Ramnagar', 'Ramnagar'),
          ('Ramngarh', 'Ramngarh'),
          ('Rampur', 'Rampur'),
          ('Rampur Maniharan', 'Rampur Maniharan'),
          ('Rampura Phul', 'Rampura Phul'),
          ('Rampurhat', 'Rampurhat'),
          ('Ranaghat', 'Ranaghat'),
          ('Ranavav', 'Ranavav'),
          ('Ranebennuru', 'Ranebennuru'),
          ('Rangia', 'Rangia'),
          ('Rania', 'Rania'),
          ('Ranibennur', 'Ranibennur'),
          ('Ranipet', 'Ranipet'),
          ('Rapar', 'Rapar'),
          ('Rasipuram', 'Rasipuram'),
          ('Rasra', 'Rasra'),
          ('Ratangarh', 'Ratangarh'),
          ('Rath', 'Rath'),
          ('Ratia', 'Ratia'),
          ('Raurkela', 'Raurkela'),
          ('Rawatbhata', 'Rawatbhata'),
          ('Rawatsar', 'Rawatsar'),
          ('Raxaul Bazar', 'Raxaul Bazar'),
          ('Rayachoti', 'Rayachoti'),
          ('Rayadurg', 'Rayadurg'),
          ('Rayagada', 'Rayagada'),
          ('Reengus', 'Reengus'),
          ('Renigunta', 'Renigunta'),
          ('Renukoot', 'Renukoot'),
          ('Reoti', 'Reoti'),
          ('Repalle', 'Repalle'),
          ('Revelganj', 'Revelganj'),
          ('Rewari', 'Rewari'),
          ('Rishikesh', 'Rishikesh'),
          ('Robertsganj', 'Robertsganj'),
          ('Robertson Pet', 'Robertson Pet'),
          ('Rohtak', 'Rohtak'),
          ('Ron', 'Ron'),
          ('Roorkee', 'Roorkee'),
          ('Rosera', 'Rosera'),
          ('Rudauli', 'Rudauli'),
          ('Rudrapur', 'Rudrapur'),
          ('Rudrapur', 'Rudrapur'),
          ('Rupnagar', 'Rupnagar'),
          ('SUrban Agglomerationr', 'SUrban Agglomerationr'),
          ('Sadabad', 'Sadabad'),
          ('Sadalagi', 'Sadalagi'),
          ('Sadasivpet', 'Sadasivpet'),
          ('Sadri', 'Sadri'),
          ('Sadulpur', 'Sadulpur'),
          ('Sadulshahar', 'Sadulshahar'),
          ('Safidon', 'Safidon'),
          ('Safipur', 'Safipur'),
          ('Sagara', 'Sagara'),
          ('Sagwara', 'Sagwara'),
          ('Saharanpur', 'Saharanpur'),
          ('Saharsa', 'Saharsa'),
          ('Sahaspur', 'Sahaspur'),
          ('Sahaswan', 'Sahaswan'),
          ('Sahawar', 'Sahawar'),
          ('Sahjanwa', 'Sahjanwa'),
          ('Saidpur', 'Saidpur'),
          ('Saiha', 'Saiha'),
          ('Sainthia', 'Sainthia'),
          ('Sakaleshapura', 'Sakaleshapura'),
          ('Sakti', 'Sakti'),
          ('Salaya', 'Salaya'),
          ('Salem', 'Salem'),
          ('Salur', 'Salur'),
          ('Samalkha', 'Samalkha'),
          ('Samalkot', 'Samalkot'),
          ('Samana', 'Samana'),
          ('Samastipur', 'Samastipur'),
          ('Sambalpur', 'Sambalpur'),
          ('Sambhal', 'Sambhal'),
          ('Sambhar', 'Sambhar'),
          ('Samdhan', 'Samdhan'),
          ('Samthar', 'Samthar'),
          ('Sanand', 'Sanand'),
          ('Sanchore', 'Sanchore'),
          ('Sandi', 'Sandi'),
          ('Sandila', 'Sandila'),
          ('Sanduru', 'Sanduru'),
          ('Sangareddy', 'Sangareddy'),
          ('Sangaria', 'Sangaria'),
          ('Sangrur', 'Sangrur'),
          ('Sankarankovil', 'Sankarankovil'),
          ('Sankari', 'Sankari'),
          ('Sankeshwara', 'Sankeshwara'),
          ('Santipur', 'Santipur'),
          ('Sardarshahar', 'Sardarshahar'),
          ('Sardhana', 'Sardhana'),
          ('Sarsod', 'Sarsod'),
          ('Sasaram', 'Sasaram'),
          ('Sathyamangalam', 'Sathyamangalam'),
          ('Sattenapalle', 'Sattenapalle'),
          ('Sattur', 'Sattur'),
          ('Saundatti-Yellamma', 'Saundatti-Yellamma'),
          ('Savanur', 'Savanur'),
          ('Savarkundla', 'Savarkundla'),
          ('Sawai Madhopur', 'Sawai Madhopur'),
          ('Sedam', 'Sedam'),
          ('Seohara', 'Seohara'),
          ('Shahabad', 'Shahabad'),
          ('Shahbad', 'Shahbad'),
          ('Shahganj', 'Shahganj'),
          ('Shahjahanpur', 'Shahjahanpur'),
          ('Shahpur', 'Shahpur'),
          ('Shahpura', 'Shahpura'),
          ('Shahpura', 'Shahpura'),
          ('Shamli', 'Shamli'),
          ('Sheikhpura', 'Sheikhpura'),
          ('Shenkottai', 'Shenkottai'),
          ('Sheoganj', 'Sheoganj'),
          ('Sheohar', 'Sheohar'),
          ('Sherghati', 'Sherghati'),
          ('Sherkot', 'Sherkot'),
          ('Shiggaon', 'Shiggaon'),
          ('Shikaripur', 'Shikaripur'),
          ('Shikohabad', 'Shikohabad'),
          ('Shillong', 'Shillong'),
          ('Shimla', 'Shimla'),
          ('Shishgarh', 'Shishgarh'),
          ('Shivamogga', 'Shivamogga'),
          ('Sholavandan', 'Sholavandan'),
          ('Sholingur', 'Sholingur'),
          ('Shoranur', 'Shoranur'),
          ('Shrirangapattana', 'Shrirangapattana'),
          ('Siana', 'Siana'),
          ('Sibsagar', 'Sibsagar'),
          ('Siddipet', 'Siddipet'),
          ('Sidhpur', 'Sidhpur'),
          ('Sidlaghatta', 'Sidlaghatta'),
          ('Sihor', 'Sihor'),
          ('Sikanderpur', 'Sikanderpur'),
          ('Sikandra Rao', 'Sikandra Rao'),
          ('Sikandrabad', 'Sikandrabad'),
          ('Sikar', 'Sikar'),
          ('Silao', 'Silao'),
          ('Silapathar', 'Silapathar'),
          ('Silchar', 'Silchar'),
          ('Siliguri', 'Siliguri'),
          ('Silvassa', 'Silvassa'),
          ('Sindagi', 'Sindagi'),
          ('Sindhagi', 'Sindhagi'),
          ('Sindhnur', 'Sindhnur'),
          ('Sira', 'Sira'),
          ('Sircilla', 'Sircilla'),
          ('Sirhind Fatehgarh Sahib', 'Sirhind Fatehgarh Sahib'),
          ('Sirkali', 'Sirkali'),
          ('Sirohi', 'Sirohi'),
          ('Sirsa', 'Sirsa'),
          ('Sirsaganj', 'Sirsaganj'),
          ('Sirsi', 'Sirsi'),
          ('Sirsi', 'Sirsi'),
          ('Siruguppa', 'Siruguppa'),
          ('Sitamarhi', 'Sitamarhi'),
          ('Sitapur', 'Sitapur'),
          ('Sitarganj', 'Sitarganj'),
          ('Sivaganga', 'Sivaganga'),
          ('Sivagiri', 'Sivagiri'),
          ('Sivakasi', 'Sivakasi'),
          ('Siwan', 'Siwan'),
          ('Sohna', 'Sohna'),
          ('Sojat', 'Sojat'),
          ('Solan', 'Solan'),
          ('Sonamukhi', 'Sonamukhi'),
          ('Sonepur', 'Sonepur'),
          ('Songadh', 'Songadh'),
          ('Sonipat', 'Sonipat'),
          ('Soro', 'Soro'),
          ('Soron', 'Soron'),
          ('Sri Madhopur', 'Sri Madhopur'),
          ('Srikakulam', 'Srikakulam'),
          ('Srikalahasti', 'Srikalahasti'),
          ('Srinagar', 'Srinagar'),
          ('Srinivaspur', 'Srinivaspur'),
          ('Srirampore', 'Srirampore'),
          ('Srisailam Project (Right Flank Colony) Township',
           'Srisailam Project (Right Flank Colony) Township'),
          ('Srivilliputhur', 'Srivilliputhur'),
          ('Sugauli', 'Sugauli'),
          ('Sujangarh', 'Sujangarh'),
          ('Sujanpur', 'Sujanpur'),
          ('Sullurpeta', 'Sullurpeta'),
          ('Sultanganj', 'Sultanganj'),
          ('Sultanpur', 'Sultanpur'),
          ('Sumerpur', 'Sumerpur'),
          ('Sumerpur', 'Sumerpur'),
          ('Sunabeda', 'Sunabeda'),
          ('Sunam', 'Sunam'),
          ('Sundargarh', 'Sundargarh'),
          ('Sundarnagar', 'Sundarnagar'),
          ('Supaul', 'Supaul'),
          ('Surandai', 'Surandai'),
          ('Surapura', 'Surapura'),
          ('Surat', 'Surat'),
          ('Suratgarh', 'Suratgarh'),
          ('Suri', 'Suri'),
          ('Suriyampalayam', 'Suriyampalayam'),
          ('Suryapet', 'Suryapet'),
          ('Tadepalligudem', 'Tadepalligudem'),
          ('Tadpatri', 'Tadpatri'),
          ('Takhatgarh', 'Takhatgarh'),
          ('Taki', 'Taki'),
          ('Talaja', 'Talaja'),
          ('Talcher', 'Talcher'),
          ('Talikota', 'Talikota'),
          ('Taliparamba', 'Taliparamba'),
          ('Talwara', 'Talwara'),
          ('Tamluk', 'Tamluk'),
          ('Tanda', 'Tanda'),
          ('Tandur', 'Tandur'),
          ('Tanuku', 'Tanuku'),
          ('Tarakeswar', 'Tarakeswar'),
          ('Taranagar', 'Taranagar'),
          ('Taraori', 'Taraori'),
          ('Tarbha', 'Tarbha'),
          ('Tarikere', 'Tarikere'),
          ('Tarn Taran', 'Tarn Taran'),
          ('Tehri', 'Tehri'),
          ('Tekkalakote', 'Tekkalakote'),
          ('Tenali', 'Tenali'),
          ('Tenkasi', 'Tenkasi'),
          ('Terdal', 'Terdal'),
          ('Tezpur', 'Tezpur'),
          ('Thakurdwara', 'Thakurdwara'),
          ('Thammampatti', 'Thammampatti'),
          ('Thana Bhawan', 'Thana Bhawan'),
          ('Thanesar', 'Thanesar'),
          ('Thangadh', 'Thangadh'),
          ('Thanjavur', 'Thanjavur'),
          ('Tharad', 'Tharad'),
          ('Tharamangalam', 'Tharamangalam'),
          ('Tharangambadi', 'Tharangambadi'),
          ('Theni Allinagaram', 'Theni Allinagaram'),
          ('Thirumangalam', 'Thirumangalam'),
          ('Thirupuvanam', 'Thirupuvanam'),
          ('Thiruthuraipoondi', 'Thiruthuraipoondi'),
          ('Thiruvalla', 'Thiruvalla'),
          ('Thiruvallur', 'Thiruvallur'),
          ('Thiruvananthapuram', 'Thiruvananthapuram'),
          ('Thiruvarur', 'Thiruvarur'),
          ('Thodupuzha', 'Thodupuzha'),
          ('Thoubal', 'Thoubal'),
          ('Thrissur', 'Thrissur'),
          ('Thuraiyur', 'Thuraiyur'),
          ('Tilda Newra', 'Tilda Newra'),
          ('Tilhar', 'Tilhar'),
          ('Tindivanam', 'Tindivanam'),
          ('Tinsukia', 'Tinsukia'),
          ('Tiptur', 'Tiptur'),
          ('Tiruchendur', 'Tiruchendur'),
          ('Tiruchengode', 'Tiruchengode'),
          ('Tiruchirappalli', 'Tiruchirappalli'),
          ('Tirukalukundram', 'Tirukalukundram'),
          ('Tirukkoyilur', 'Tirukkoyilur'),
          ('Tirunelveli', 'Tirunelveli'),
          ('Tirupathur', 'Tirupathur'),
          ('Tirupathur', 'Tirupathur'),
          ('Tirupati', 'Tirupati'),
          ('Tiruppur', 'Tiruppur'),
          ('Tirur', 'Tirur'),
          ('Tiruttani', 'Tiruttani'),
          ('Tiruvannamalai', 'Tiruvannamalai'),
          ('Tiruvethipuram', 'Tiruvethipuram'),
          ('Tiruvuru', 'Tiruvuru'),
          ('Tirwaganj', 'Tirwaganj'),
          ('Titlagarh', 'Titlagarh'),
          ('Tittakudi', 'Tittakudi'),
          ('Todabhim', 'Todabhim'),
          ('Todaraisingh', 'Todaraisingh'),
          ('Tohana', 'Tohana'),
          ('Tonk', 'Tonk'),
          ('Tuensang', 'Tuensang'),
          ('Tulsipur', 'Tulsipur'),
          ('Tumkur', 'Tumkur'),
          ('Tundla', 'Tundla'),
          ('Tuni', 'Tuni'),
          ('Tura', 'Tura'),
          ('Udaipur', 'Udaipur'),
          ('Udaipur', 'Udaipur'),
          ('Udaipurwati', 'Udaipurwati'),
          ('Udhagamandalam', 'Udhagamandalam'),
          ('Udumalaipettai', 'Udumalaipettai'),
          ('Udupi', 'Udupi'),
          ('Ujhani', 'Ujhani'),
          ('Umbergaon', 'Umbergaon'),
          ('Umreth', 'Umreth'),
          ('Una', 'Una'),
          ('Unjha', 'Unjha'),
          ('Unnamalaikadai', 'Unnamalaikadai'),
          ('Unnao', 'Unnao'),
          ('Upleta', 'Upleta'),
          ('Uravakonda', 'Uravakonda'),
          ('Urmar Tanda', 'Urmar Tanda'),
          ('Usilampatti', 'Usilampatti'),
          ('Uthamapalayam', 'Uthamapalayam'),
          ('Uthiramerur', 'Uthiramerur'),
          ('Utraula', 'Utraula'),
          ('Vadakkuvalliyur', 'Vadakkuvalliyur'),
          ('Vadalur', 'Vadalur'),
          ('Vadipatti', 'Vadipatti'),
          ('Vadnagar', 'Vadnagar'),
          ('Vadodara', 'Vadodara'),
          ('Vaikom', 'Vaikom'),
          ('Valparai', 'Valparai'),
          ('Valsad', 'Valsad'),
          ('Vandavasi', 'Vandavasi'),
          ('Vaniyambadi', 'Vaniyambadi'),
          ('Vapi', 'Vapi'),
          ('Vapi', 'Vapi'),
          ('Varanasi', 'Varanasi'),
          ('Varkala', 'Varkala'),
          ('Vatakara', 'Vatakara'),
          ('Vedaranyam', 'Vedaranyam'),
          ('Vellakoil', 'Vellakoil'),
          ('Vellore', 'Vellore'),
          ('Venkatagiri', 'Venkatagiri'),
          ('Veraval', 'Veraval'),
          ('Vijapur', 'Vijapur'),
          ('Vijayapura', 'Vijayapura'),
          ('Vijayawada', 'Vijayawada'),
          ('Vikarabad', 'Vikarabad'),
          ('Vikramasingapuram', 'Vikramasingapuram'),
          ('Viluppuram', 'Viluppuram'),
          ('Vinukonda', 'Vinukonda'),
          ('Viramgam', 'Viramgam'),
          ('Virudhachalam', 'Virudhachalam'),
          ('Virudhunagar', 'Virudhunagar'),
          ('Visakhapatnam', 'Visakhapatnam'),
          ('Visnagar', 'Visnagar'),
          ('Viswanatham', 'Viswanatham'),
          ('Vizianagaram', 'Vizianagaram'),
          ('Vrindavan', 'Vrindavan'),
          ('Vyara', 'Vyara'),
          ('Wadhwan', 'Wadhwan'),
          ('Wadi', 'Wadi'),
          ('Wanaparthy', 'Wanaparthy'),
          ('Wankaner', 'Wankaner'),
          ('Warangal', 'Warangal'),
          ('Warhapur', 'Warhapur'),
          ('Warisaliganj', 'Warisaliganj'),
          ('Wokha', 'Wokha'),
          ('Yadgir', 'Yadgir'),
          ('Yamunanagar', 'Yamunanagar'),
          ('Yanam', 'Yanam'),
          ('Yellandu', 'Yellandu'),
          ('Yemmiganur', 'Yemmiganur'),
          ('Yerraguntla', 'Yerraguntla'),
          ('Zaidpur', 'Zaidpur'),
          ('Zamania', 'Zamania'),
          ('Zira', 'Zira'),
          ('Zirakpur', 'Zirakpur'),
          ('Ahmadnagar (Ahmednagar)', 'Ahmadnagar (Ahmednagar)'),
          ('Akola', 'Akola'),
          ('Amravati', 'Amravati'),
          ('Aurangabad', 'Aurangabad'),
          ('Bhandara', 'Bhandara'),
          ('Bid (Beed)', 'Bid (Beed)'),
          ('Buldana (Buldhana)', 'Buldana (Buldhana)'),
          ('Chandrapur', 'Chandrapur'),
          ('Dhule', 'Dhule'),
          ('Gadchiroli', 'Gadchiroli'),
          ('Gondiya (Gondia)', 'Gondiya (Gondia)'),
          ('Hingoli', 'Hingoli'),
          ('Jalgaon', 'Jalgaon'),
          ('Jalna', 'Jalna'),
          ('Kolhapur', 'Kolhapur'),
          ('Latur', 'Latur'),
          ('Mumbai', 'Mumbai'),
          ('Mumbai Suburban', 'Mumbai Suburban'),
          ('Nagpur', 'Nagpur'),
          ('Nanded', 'Nanded'),
          ('Nandurbar', 'Nandurbar'),
          ('Nashik', 'Nashik'),
          ('Osmanabad', 'Osmanabad'),
          ('Parbhani', 'Parbhani'),
          ('Pune', 'Pune'),
          ('Raigad', 'Raigad'),
          ('Ratnagiri', 'Ratnagiri'),
          ('Sangli', 'Sangli'),
          ('Satara', 'Satara'),
          ('Sindhudurg', 'Sindhudurg'),
          ('Solapur', 'Solapur'),
          ('Thane', 'Thane'),
          ('Wardha', 'Wardha'),
          ('Washim', 'Washim'),
          ('Yavatmal', 'Yavatmal'),
          ('Indore', 'Indore'), ('Bhopal', 'Bhopal'), ('Jabalpur', 'Jabalpur'),
          ('Gwalior', 'Gwalior'), ('Ujjain', 'Ujjain'), ('Sagar', 'Sagar'),
          ('Dewas', 'Dewas'), ('Satna', 'Satna'), ('Ratlam', 'Ratlam'),
          ('Rewa', 'Rewa'), ('Murwara (Katni)', 'Murwara (Katni)'),
          ('Singrauli', 'Singrauli'), ('Burhanpur', 'Burhanpur'),
          ('Khandwa', 'Khandwa'), ('Bhind', 'Bhind'),
          ('Chhindwara', 'Chhindwara'), ('Guna', 'Guna'),
          ('Shivpuri', 'Shivpuri'), ('Vidisha', 'Vidisha'),
          ('Chhatarpur', 'Chhatarpur'), ('Damoh', 'Damoh'),
          ('Mandsaur', 'Mandsaur'), ('Khargone', 'Khargone'),
          ('Neemuch', 'Neemuch'), ('Pithampur', 'Pithampur'),
          ('Hoshangabad', 'Hoshangabad'), ('Itarsi', 'Itarsi'),
          ('Sehore', 'Sehore'), ('Betul', 'Betul'), ('Seoni', 'Seoni'),
          ('Datia', 'Datia'), ('Nagda', 'Nagda')
          )

STATES = (
    (None, '-Select State-'),
    ('Andhra Pradesh', 'Andhra Pradesh'),
    ('Arunachal Pradesh', 'Arunachal Pradesh'),
    ('Assam', 'Assam'),
    ('Bihar', 'Bihar'),
    ('Chandigarh', 'Chandigarh'),
    ('Chhattisgarh', 'Chhattisgarh'),
    ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'),
    ('Delhi', 'Delhi'),
    ('Goa', 'Goa'),
    ('Gujarat', 'Gujarat'),
    ('Haryana', 'Haryana'),
    ('Himachal Pradesh', 'Himachal Pradesh'),
    ('Karnataka', 'Karnataka'),
    ('Kerala', 'Kerala'),
    ('Maharashtra', 'Maharashtra'),
    ('Madhya Pradesh', 'Madhya Pradesh'),
    ('Manipur', 'Manipur'),
    ('Meghalaya', 'Meghalaya'),
    ('Mizoram', 'Mizoram'),
    ('Nagaland', 'Nagaland'),
    ('Odisha', 'Odisha'),
    ('Puducherry', 'Puducherry'),
    ('Punjab', 'Punjab'),
    ('Rajasthan', 'Rajasthan'),
    ('Tamil Nadu', 'Tamil Nadu'),
    ('Telangana', 'Telangana'),
    ('Tripura', 'Tripura'),
    ('Uttar Pradesh', 'Uttar Pradesh'),
    ('Uttarakhand', 'Uttarakhand'),
    ('West Bengal', 'West Bengal'),
)

STATE_N_CITY = {
    'Delhi': ['-Select City-', 'Delhi', 'New Delhi'],
    'Karnataka': ['-Select City-', 'Bengaluru', 'Hubli-Dharwad',
                  'Belagavi', 'Mangaluru',
                  'Davanagere', 'Ballari', 'Tumkur', 'Shivamogga',
                  'Raayachuru', 'Robertson Pet', 'Kolar', 'Mandya',
                  'Udupi',
                  'Chikkamagaluru', 'Karwar', 'Ranebennuru',
                  'Ranibennur',
                  'Ramanagaram', 'Gokak', 'Yadgir',
                  'Rabkavi Banhatti',
                  'Shahabad', 'Sirsi', 'Sindhnur', 'Tiptur',
                  'Arsikere',
                  'Nanjangud', 'Sagara', 'Sira', 'Puttur', 'Athni',
                  'Mulbagal',
                  'Surapura', 'Siruguppa', 'Mudhol', 'Sidlaghatta',
                  'Shahpur',
                  'Saundatti-Yellamma', 'Wadi', 'Manvi',
                  'Nelamangala',
                  'Lakshmeshwar', 'Ramdurg', 'Nargund', 'Tarikere',
                  'Malavalli', 'Savanur', 'Lingsugur',
                  'Vijayapura',
                  'Sankeshwara', 'Madikeri', 'Talikota', 'Sedam',
                  'Shikaripur',
                  'Mahalingapura', 'Mudalagi', 'Muddebihal',
                  'Pavagada',
                  'Malur', 'Sindhagi', 'Sanduru', 'Afzalpur',
                  'Maddur',
                  'Madhugiri', 'Tekkalakote', 'Terdal',
                  'Mudabidri', 'Magadi',
                  'Navalgund', 'Shiggaon', 'Shrirangapattana',
                  'Sindagi',
                  'Sakaleshapura', 'Srinivaspur', 'Ron',
                  'Mundargi',
                  'Sadalagi', 'Piriyapatna', 'Adyar'],
    'Gujarat': ['-Select City-', 'Ahmedabad', 'Surat', 'Vadodara',
                'Rajkot', 'Bhavnagar',
                'Jamnagar', 'Nadiad', 'Porbandar', 'Anand',
                'Morvi',
                'Mahesana', 'Bharuch', 'Vapi', 'Navsari',
                'Veraval', 'Bhuj',
                'Godhra', 'Palanpur', 'Valsad', 'Patan', 'Deesa',
                'Amreli',
                'Anjar', 'Dhoraji', 'Khambhat', 'Mahuva', 'Keshod',
                'Wadhwan',
                'Ankleshwar', 'Savarkundla', 'Kadi', 'Visnagar',
                'Upleta',
                'Una', 'Sidhpur', 'Unjha', 'Mangrol', 'Viramgam',
                'Modasa',
                'Palitana', 'Petlad', 'Kapadvanj', 'Sihor',
                'Wankaner',
                'Limbdi', 'Mandvi', 'Thangadh', 'Vyara', 'Padra',
                'Lunawada',
                'Rajpipla', 'Vapi', 'Umreth', 'Sanand', 'Rajula',
                'Radhanpur',
                'Mahemdabad', 'Ranavav', 'Tharad', 'Mansa',
                'Umbergaon',
                'Talaja', 'Vadnagar', 'Manavadar', 'Salaya',
                'Vijapur',
                'Pardi', 'Rapar', 'Songadh', 'Lathi', 'Adalaj',
                'Chhapra'],
    'Madhya Pradesh': ['-Select City-', 'Indore', 'Bhopal', 'Jabalpur',
                       'Gwalior', 'Ujjain', 'Sagar', 'Dewas', 'Satna',
                       'Ratlam', 'Rewa', 'Murwara (Katni)', 'Singrauli',
                       'Burhanpur', 'Khandwa', 'Bhind', 'Chhindwara', 'Guna',
                       'Shivpuri', 'Vidisha', 'Chhatarpur', 'Damoh',
                       'Mandsaur', 'Khargone', 'Neemuch', 'Pithampur',
                       'Hoshangabad', 'Itarsi', 'Sehore', 'Betul', 'Seoni',
                       'Datia', 'Nagda'],
    'Telangana': ['-Select City-', 'Hyderabad', 'Warangal',
                  'Nizamabad', 'Karimnagar',
                  'Ramagundam', 'Khammam', 'Mahbubnagar',
                  'Mancherial',
                  'Adilabad', 'Suryapet', 'Jagtial', 'Miryalaguda',
                  'Nirmal',
                  'Kamareddy', 'Kothagudem', 'Bodhan', 'Palwancha',
                  'Mandamarri', 'Koratla', 'Sircilla', 'Tandur',
                  'Siddipet',
                  'Wanaparthy', 'Kagaznagar', 'Gadwal',
                  'Sangareddy',
                  'Bellampalle', 'Bhongir', 'Vikarabad', 'Jangaon',
                  'Bhadrachalam', 'Bhainsa', 'Farooqnagar',
                  'Medak',
                  'Narayanpet', 'Sadasivpet', 'Yellandu',
                  'Manuguru',
                  'Kyathampalle', 'Nagarkurnool'],
    'Tamil Nadu': ['-Select City-', 'Chennai', 'Coimbatore',
                   'Madurai', 'Tiruchirappalli',
                   'Salem', 'Tirunelveli', 'Tiruppur', 'Ranipet',
                   'Nagercoil',
                   'Thanjavur', 'Vellore', 'Kancheepuram', 'Erode',
                   'Tiruvannamalai', 'Pollachi', 'Rajapalayam',
                   'Sivakasi',
                   'Pudukkottai', 'Neyveli (TS)', 'Nagapattinam',
                   'Viluppuram',
                   'Tiruchengode', 'Vaniyambadi',
                   'Theni Allinagaram',
                   'Udhagamandalam', 'Aruppukkottai', 'Paramakudi',
                   'Arakkonam', 'Virudhachalam', 'Srivilliputhur',
                   'Tindivanam', 'Virudhunagar', 'Karur',
                   'Valparai',
                   'Sankarankovil', 'Tenkasi', 'Palani',
                   'Pattukkottai',
                   'Tirupathur', 'Ramanathapuram',
                   'Udumalaipettai',
                   'Gobichettipalayam', 'Thiruvarur',
                   'Thiruvallur', 'Panruti',
                   'Namakkal', 'Thirumangalam',
                   'Vikramasingapuram',
                   'Nellikuppam', 'Rasipuram', 'Tiruttani',
                   'Nandivaram-Guduvancheri', 'Periyakulam',
                   'Pernampattu',
                   'Vellakoil', 'Sivaganga', 'Vadalur',
                   'Rameshwaram',
                   'Tiruvethipuram', 'Perambalur', 'Usilampatti',
                   'Vedaranyam',
                   'Sathyamangalam', 'Puliyankudi', 'Nanjikottai',
                   'Thuraiyur',
                   'Sirkali', 'Tiruchendur', 'Periyasemur',
                   'Sattur',
                   'Vandavasi', 'Tharamangalam', 'Tirukkoyilur',
                   'Oddanchatram', 'Palladam', 'Vadakkuvalliyur',
                   'Tirukalukundram', 'Uthamapalayam', 'Surandai',
                   'Sankari',
                   'Shenkottai', 'Vadipatti', 'Sholingur',
                   'Tirupathur',
                   'Manachanallur', 'Viswanatham', 'Polur',
                   'Panagudi',
                   'Uthiramerur', 'Thiruthuraipoondi',
                   'Pallapatti', 'Ponneri',
                   'Lalgudi', 'Natham', 'Unnamalaikadai',
                   'P.N.Patti',
                   'Tharangambadi', 'Tittakudi', 'Pacode',
                   "O' Valley",
                   'Suriyampalayam', 'Sholavandan', 'Thammampatti',
                   'Namagiripettai', 'Peravurani', 'Parangipettai',
                   'Pudupattinam', 'Pallikonda', 'Sivagiri',
                   'Punjaipugalur',
                   'Padmanabhapuram', 'Thirupuvanam'],
    'West Bengal': ['-Select City-', 'Kolkata', 'Siliguri',
                    'Asansol', 'Raghunathganj',
                    'Kharagpur', 'Naihati', 'English Bazar',
                    'Baharampur',
                    'Hugli-Chinsurah', 'Raiganj', 'Jalpaiguri',
                    'Santipur',
                    'Balurghat', 'Medinipur', 'Habra', 'Ranaghat',
                    'Bankura',
                    'Nabadwip', 'Darjiling', 'Purulia', 'Arambagh',
                    'Tamluk',
                    'AlipurdUrban Agglomerationr', 'Suri',
                    'Jhargram',
                    'Gangarampur', 'Rampurhat', 'Kalimpong',
                    'Sainthia',
                    'Taki', 'Murshidabad', 'Memari',
                    'Paschim Punropara',
                    'Tarakeswar', 'Sonamukhi',
                    'PandUrban Agglomeration',
                    'Mainaguri', 'Malda', 'Panchla',
                    'Raghunathpur',
                    'Mathabhanga', 'Monoharpur', 'Srirampore',
                    'Adra'],
    'Rajasthan': ['-Select City-', 'Jaipur', 'Jodhpur', 'Bikaner',
                  'Udaipur', 'Ajmer',
                  'Bhilwara', 'Alwar', 'Bharatpur', 'Pali',
                  'Barmer', 'Sikar',
                  'Tonk', 'Sadulpur', 'Sawai Madhopur', 'Nagaur',
                  'Makrana',
                  'Sujangarh', 'Sardarshahar', 'Ladnu',
                  'Ratangarh', 'Nokha',
                  'Nimbahera', 'Suratgarh', 'Rajsamand',
                  'Lachhmangarh',
                  'Rajgarh (Churu)', 'Nasirabad', 'Nohar',
                  'Phalodi',
                  'Nathdwara', 'Pilani', 'Merta City', 'Sojat',
                  'Neem-Ka-Thana', 'Sirohi', 'Pratapgarh',
                  'Rawatbhata',
                  'Sangaria', 'Lalsot', 'Pilibanga', 'Pipar City',
                  'Taranagar',
                  'Sumerpur', 'Sagwara', 'Ramganj Mandi',
                  'Lakheri',
                  'Udaipurwati', 'Losal', 'Sri Madhopur',
                  'Ramngarh',
                  'Rawatsar', 'Rajakhera', 'Shahpura', 'Shahpura',
                  'Raisinghnagar', 'Malpura', 'Nadbai', 'Sanchore',
                  'Nagar',
                  'Rajgarh (Alwar)', 'Sheoganj', 'Sadri',
                  'Todaraisingh',
                  'Todabhim', 'Reengus', 'Rajaldesar',
                  'Sadulshahar',
                  'Sambhar', 'Prantij', 'Mount Abu', 'Mangrol',
                  'Phulera',
                  'Mandawa', 'Pindwara', 'Mandalgarh',
                  'Takhatgarh'],
    'Uttar Pradesh': ['-Select City-', 'Lucknow', 'Kanpur',
                      'Firozabad', 'Agra', 'Meerut',
                      'Varanasi', 'Allahabad', 'Amroha',
                      'Moradabad',
                      'Aligarh', 'Saharanpur', 'Noida', 'Loni',
                      'Jhansi', 'Ghaziabad',
                      'Shahjahanpur', 'Rampur', 'Modinagar',
                      'Hapur', 'Etawah',
                      'Sambhal', 'Orai', 'Bahraich', 'Unnao',
                      'Rae Bareli',
                      'Lakhimpur', 'Sitapur', 'Lalitpur',
                      'Pilibhit',
                      'Chandausi', 'Hardoi', 'Azamgarh', 'Khair',
                      'Sultanpur',
                      'Tanda', 'Nagina', 'Shamli', 'Najibabad',
                      'Shikohabad',
                      'Sikandrabad', 'Pilkhuwa', 'Renukoot',
                      'Vrindavan',
                      'Ujhani', 'Laharpur', 'Tilhar', 'Sahaswan',
                      'Rath',
                      'Sherkot', 'Kalpi', 'Tundla', 'Sandila',
                      'Nanpara',
                      'Sardhana', 'Nehtaur', 'Seohara', 'Padrauna',
                      'Mathura',
                      'Thakurdwara', 'Nawabganj', 'Siana',
                      'Noorpur',
                      'Sikandra Rao', 'Puranpur', 'Rudauli',
                      'Thana Bhawan',
                      'Palia Kalan', 'Zaidpur', 'Nautanwa',
                      'Zamania',
                      'Naugawan Sadat', 'Fatehpur Sikri',
                      'Robertsganj',
                      'Utraula', 'Sadabad', 'Rasra', 'Lar',
                      'Lal Gopalganj Nindaura', 'Sirsaganj',
                      'Pihani',
                      'Rudrapur', 'Soron', 'SUrban Agglomerationr',
                      'Samdhan',
                      'Sahjanwa', 'Rampur Maniharan', 'Sumerpur',
                      'Shahganj',
                      'Tulsipur', 'Tirwaganj',
                      'PurqUrban Agglomerationzi',
                      'Warhapur', 'Powayan', 'Sandi', 'Achhnera',
                      'Naraura',
                      'Nakur', 'Sahaspur', 'Safipur', 'Reoti',
                      'Sikanderpur',
                      'Saidpur', 'Sirsi', 'Purwa', 'Parasi',
                      'Lalganj',
                      'Phulpur', 'Shishgarh', 'Sahawar', 'Samthar',
                      'Pukhrayan', 'Obra', 'Niwai'],
    'Bihar': ['-Select City-', 'Patna', 'Gaya', 'Bhagalpur',
              'Muzaffarpur', 'Darbhanga',
              'Arrah', 'Begusarai', 'Chhapra', 'Katihar', 'Munger',
              'Purnia',
              'Saharsa', 'Sasaram', 'Hajipur', 'Dehri-on-Sone',
              'Bettiah',
              'Motihari', 'Bagaha', 'Siwan', 'Kishanganj',
              'Jamalpur', 'Buxar',
              'Jehanabad', 'Aurangabad', 'Lakhisarai', 'Nawada',
              'Jamui',
              'Sitamarhi', 'Araria', 'Gopalganj', 'Madhubani',
              'Masaurhi',
              'Samastipur', 'Mokameh', 'Supaul', 'Dumraon',
              'Arwal',
              'Forbesganj', 'BhabUrban Agglomeration',
              'Narkatiaganj',
              'Naugachhia', 'Madhepura', 'Sheikhpura',
              'Sultanganj',
              'Raxaul Bazar', 'Ramnagar', 'Mahnar Bazar',
              'Warisaliganj',
              'Revelganj', 'Rajgir', 'Sonepur', 'Sherghati',
              'Sugauli',
              'Makhdumpur', 'Maner', 'Rosera', 'Nokha', 'Piro',
              'Rafiganj',
              'Marhaura', 'Mirganj', 'Lalganj', 'Murliganj',
              'Motipur',
              'Manihari', 'Sheohar', 'Maharajganj', 'Silao',
              'Barh',
              'Asarganj'],
    'Andhra Pradesh': ['-Select City-', 'Visakhapatnam',
                       'Vijayawada', 'Guntur', 'Nellore',
                       'Kurnool', 'Rajahmundry', 'Kakinada',
                       'Tirupati',
                       'Anantapur', 'Kadapa', 'Vizianagaram',
                       'Eluru',
                       'Ongole', 'Nandyal', 'Machilipatnam',
                       'Adoni', 'Tenali',
                       'Chittoor', 'Hindupur', 'Proddatur',
                       'Bhimavaram',
                       'Madanapalle', 'Guntakal', 'Dharmavaram',
                       'Gudivada',
                       'Srikakulam', 'Narasaraopet', 'Rajampet',
                       'Tadpatri',
                       'Tadepalligudem', 'Chilakaluripet',
                       'Yemmiganur',
                       'Kadiri', 'Chirala', 'Anakapalle', 'Kavali',
                       'Palacole',
                       'Sullurpeta', 'Tanuku', 'Rayachoti',
                       'Srikalahasti',
                       'Bapatla', 'Naidupet', 'Nagari', 'Gudur',
                       'Vinukonda',
                       'Narasapuram', 'Nuzvid', 'Markapur',
                       'Ponnur',
                       'Kandukur', 'Bobbili', 'Rayadurg',
                       'Samalkot',
                       'Jaggaiahpet', 'Tuni', 'Amalapuram',
                       'Bheemunipatnam',
                       'Venkatagiri', 'Sattenapalle', 'Pithapuram',
                       'Palasa Kasibugga', 'Parvathipuram',
                       'Macherla',
                       'Gooty', 'Salur', 'Mandapeta',
                       'Jammalamadugu',
                       'Peddapuram', 'Punganur', 'Nidadavole',
                       'Repalle',
                       'Ramachandrapuram', 'Kovvur', 'Tiruvuru',
                       'Uravakonda',
                       'Narsipatnam', 'Yerraguntla', 'Pedana',
                       'Puttur',
                       'Renigunta', 'Rajam',
                       'Srisailam Project (Right Flank Colony) Township'],
    'Punjab': ['-Select City-', 'Ludhiana', 'Patiala', 'Amritsar',
               'Jalandhar', 'Bathinda',
               'Pathankot', 'Hoshiarpur', 'Batala', 'Moga',
               'Malerkotla',
               'Khanna', 'Mohali', 'Barnala', 'Firozpur',
               'Phagwara',
               'Kapurthala', 'Zirakpur', 'Kot Kapura', 'Faridkot',
               'Muktsar',
               'Rajpura', 'Sangrur', 'Fazilka', 'Gurdaspur',
               'Kharar',
               'Gobindgarh', 'Mansa', 'Malout', 'Nabha',
               'Tarn Taran',
               'Jagraon', 'Sunam', 'Dhuri', 'Firozpur Cantt.',
               'Sirhind Fatehgarh Sahib', 'Rupnagar',
               'Jalandhar Cantt.',
               'Samana', 'Nawanshahr', 'Rampura Phul', 'Nangal',
               'Nakodar',
               'Zira', 'Patti', 'Raikot', 'Longowal',
               'Urmar Tanda',
               'Phillaur', 'Pattran', 'Qadian', 'Sujanpur',
               'Mukerian',
               'Talwara'],
    'Haryana': ['-Select City-', 'Faridabad', 'Gurgaon', 'Hisar',
                'Rohtak', 'Panipat', 'Karnal',
                'Sonipat', 'Yamunanagar', 'Panchkula', 'Bhiwani',
                'Bahadurgarh', 'Jind', 'Sirsa', 'Thanesar',
                'Kaithal',
                'Palwal', 'Rewari', 'Hansi', 'Narnaul',
                'Fatehabad', 'Gohana',
                'Tohana', 'Narwana', 'Mandi Dabwali',
                'Charkhi Dadri',
                'Shahbad', 'Pehowa', 'Samalkha', 'Pinjore',
                'Ladwa', 'Sohna',
                'Safidon', 'Taraori', 'Mahendragarh', 'Ratia',
                'Rania',
                'Sarsod'],
    'Chhattisgarh': ['-Select City-', 'Raipur', 'Bhilai Nagar',
                     'Korba', 'Bilaspur', 'Durg',
                     'Rajnandgaon', 'Jagdalpur', 'Raigarh',
                     'Ambikapur',
                     'Mahasamund', 'Dhamtari', 'Chirmiri',
                     'Bhatapara',
                     'Dalli-Rajhara', 'Naila Janjgir',
                     'Tilda Newra',
                     'Mungeli', 'Manendragarh', 'Sakti'],
    'Assam': ['-Select City-', 'Guwahati', 'Silchar', 'Dibrugarh',
              'Nagaon', 'Tinsukia',
              'Jorhat', 'Bongaigaon City', 'Dhubri', 'Diphu',
              'North Lakhimpur', 'Tezpur', 'Karimganj', 'Sibsagar',
              'Goalpara',
              'Barpeta', 'Lanka', 'Lumding', 'Mankachar',
              'Nalbari', 'Rangia',
              'Margherita', 'Mangaldoi', 'Silapathar', 'Mariani',
              'Marigaon'],
    'Chandigarh': ['-Select City-', 'Chandigarh'],
    'Odisha': ['-Select City-', 'Bhubaneswar', 'Cuttack',
               'Raurkela', 'Brahmapur', 'Sambalpur',
               'Puri', 'Baleshwar Town', 'Baripada Town',
               'Bhadrak',
               'Balangir', 'Jharsuguda', 'Bargarh', 'Paradip',
               'Bhawanipatna',
               'Dhenkanal', 'Barbil', 'Kendujhar', 'Sunabeda',
               'Rayagada',
               'Jatani', 'Byasanagar', 'Kendrapara',
               'Rajagangapur',
               'Parlakhemundi', 'Talcher', 'Sundargarh',
               'Phulabani',
               'Pattamundai', 'Titlagarh', 'Nabarangapur', 'Soro',
               'Malkangiri', 'Rairangpur', 'Tarbha'],
    'Kerala': ['-Select City-', 'Thiruvananthapuram', 'Kochi',
               'Kozhikode', 'Kollam',
               'Thrissur', 'Palakkad', 'Alappuzha', 'Malappuram',
               'Ponnani',
               'Vatakara', 'Kanhangad', 'Taliparamba', 'Koyilandy',
               'Neyyattinkara', 'Kayamkulam', 'Nedumangad',
               'Kannur', 'Tirur',
               'Kottayam', 'Kasaragod', 'Kunnamkulam',
               'Ottappalam',
               'Thiruvalla', 'Thodupuzha', 'Chalakudy',
               'Changanassery',
               'Punalur', 'Nilambur', 'Cherthala',
               'Perinthalmanna',
               'Mattannur', 'Shoranur', 'Varkala', 'Paravoor',
               'Pathanamthitta', 'Peringathur', 'Attingal',
               'Kodungallur',
               'Pappinisseri', 'Chittur-Thathamangalam',
               'Muvattupuzha',
               'Adoor', 'Mavelikkara', 'Mavoor', 'Perumbavoor',
               'Vaikom',
               'Palai', 'Panniyannur', 'Guruvayoor', 'Puthuppally',
               'Panamattom'],
    'Uttarakhand': ['-Select City-', 'Dehradun', 'Hardwar',
                    'Haldwani-cum-Kathgodam',
                    'Srinagar', 'Kashipur', 'Roorkee', 'Rudrapur',
                    'Rishikesh',
                    'Ramnagar', 'Pithoragarh', 'Manglaur',
                    'Nainital',
                    'Mussoorie', 'Tehri', 'Pauri', 'Nagla',
                    'Sitarganj',
                    'Bageshwar'],
    'Puducherry': ['-Select City-', 'Pondicherry', 'Karaikal',
                   'Yanam', 'Mahe'],
    'Tripura': ['-Select City-', 'Agartala', 'Udaipur',
                'Dharmanagar', 'Pratapgarh',
                'Kailasahar', 'Belonia', 'Khowai'],
    'Mizoram': ['-Select City-', 'Aizawl', 'Lunglei', 'Saiha'],
    'Meghalaya': ['-Select City-', 'Shillong', 'Tura',
                  'Nongstoin'],
    'Manipur': ['-Select City-', 'Imphal', 'Thoubal', 'Lilong',
                'Mayang Imphal'],
    'Himachal Pradesh': ['-Select City-', 'Shimla', 'Mandi',
                         'Solan', 'Nahan', 'Sundarnagar',
                         'Palampur'],
    'Nagaland': ['-Select City-', 'Dimapur', 'Kohima', 'Zunheboto',
                 'Tuensang', 'Wokha',
                 'Mokokchung'],
    'Goa': ['-Select City-', 'Marmagao', 'Panaji', 'Margao',
            'Mapusa'],
    'Arunachal Pradesh': ['-Select City-', 'Naharlagun',
                          'Pasighat'],
    'Dadra and Nagar Haveli': ['-Select City-', 'Silvassa'],
    'Maharashtra': ['-Select City-',
                    'Ahmadnagar(Ahmednagar)',
                    'Akola',
                    'Amravati',
                    'Aurangabad',
                    'Bhandara',
                    'Bid (Beed)',
                    'Buldana (Buldhana)',
                    'Chandrapur',
                    'Dhule',
                    'Gadchiroli',
                    'Gondiya (Gondia)',
                    'Hingoli',
                    'Jalgaon',
                    'Jalna',
                    'Kolhapur',
                    'Latur',
                    'Mumbai',
                    'Mumbai Suburban',
                    'Nagpur',
                    'Nanded',
                    'Nandurbar',
                    'Nashik',
                    'Osmanabad',
                    'Parbhani',
                    'Pune',
                    'Raigad',
                    'Ratnagiri',
                    'Sangli',
                    'Satara',
                    'Sindhudurg',
                    'Solapur',
                    'Thane',
                    'Wardha',
                    'Washim',
                    'Yavatmal'
                    ]
}

UNIT = ((None, '-Select Unit-'),
        ('mg/l', 'mg/l'),
        ('C', 'C',),
        ('pH', 'pH'),
        ('%', '%',),
        ('µg/m3', 'µg/m3'),
        ('celsius', 'celsius'),
        ('Deg', 'Deg'),
        ('Hazen-eq.', 'Hazen-eq.'),
        ('hu', 'hu'),
        ('m/sec', 'm/sec'),
        ('m3/h', 'm3/h'),
        ('m3/hr', 'm3/hr'),
        ('mg/Nm3', 'mg/Nm3'),
        ('mm', 'mm'),
        ('mm-Hg', 'mm-Hg'),
        ('NTU', 'NTU'),
        ('ppb', 'ppb'),
        ('units', 'units'),
        ('uS/cm', 'uS/cm'),
        ('w/m2', 'w/m2'),
        ('mld', 'mld'),
        ('mlu', 'mlu'),
        ('l/h', 'l/h'),
        ('kg/hr', 'kg/hr'),
        ('myUnit1', 'myUnit1'),
        ('I/hr', 'I/hr'),
        ('m', 'm'),
        ('m3/s', 'm3/s'),
        ('ppm', 'ppm'),)

HTML_COLOR = [
    '#808080',
    '#000000',
    '#FF0000',
    '#800000',
    '#FFFF00',
    '#808000',
    '#00FF00',
    '#008000',
    '#00FFFF',
    '#008080',
    '#0000FF',
    '#000080',
    '#FF00FF',
    '#800080',
    '#DB7093',
    '#B0E0E6',
    '#800080',
    '#663399',
    '#4169E1',
    '#00FF7F',
    '#4682B4',
    '#008080',
    '#2E8B57',
    '#A52A2A',
]

PCB_API_ERRORS = {
    'ERROR 1001': 'Issues or missing header Timestamp.',
    'ERROR 1002': 'Issues or missing header Authorization.',
    'ERROR E_1003': 'Issues or missing header site Id',
    'ERROR 1004': 'Missing headers',
    'ERROR 1005': 'Invalid Request, Request Format',
    'ERROR 1007': 'Invalid Request, Request Format',
    'ERROR 1008': 'Invalid Request, Request Format',
    'ERROR 1006 TYPE1': 'Invalid Site Details, Header Information Missing',
    'ERROR 1006 TYPE2': 'Error in Encryption. Missing fields in header',
    'ERROR 1006 TYPE3': 'Site ID Mismatch in Header',
    'ERROR 1006 TYPE4': 'Timestamp Mismatch in Header',
    'ERROR 1006 TYPE5': 'Software Version Mismatch in Header',
    'ERROR 1006 TYPE6': 'Timestamp not within the Required Timeframe, '
                        '(Either Filestamps are of future date or Timestamp '
                        'in header is incorrect)',
    'ERROR 1006 TYPE7': 'Invalid Details in Request. Error in Encryption'
}

MPCB_METADATA = ['SITE_ID', 'SITE_UID', 'MONITORING_UNIT_ID', 'ANALYZER_ID',
                 'PARAMETER_ID', 'PARAMETER_NAME', 'READING', 'UNIT_ID',
                 'DATA_QUALITY_CODE', 'RAW_READING', 'UNIX_TIMESTAMP',
                 'CALIBRATION_FLAG', 'MAINTENANCE_FLAG']

REPORT_TYPE = (
    ('LODR', 'Live Offline Delay Report'),
    ('LOR', 'Latest Offline Report'),
    ('INDUSTRIES', 'Industries Added Report'),
    ('MBR', 'Monthly Backup Report'),
    ('SMSR', 'SMS Report'),
    ('SDR', 'Station Data Report'),
    ('CPCBAR', 'CPCB Alarm Report'),
    ('SHR', 'Station Halt Report'),
    ('DR', 'Distillery Report'),
    ('CRPR', 'CRP Report'),
)

ISO_CODES = {'PM': '22/23', 'pH': '50', 'NOx': '35', 'PM10': '24',
             'PM2.5': '39', 'O3': '8', 'SO2': '1', 'CO': '4',
             'NO2': '3',
             'IR Radiation': '71', 'UV Radiation': '72',
             'Humidity': '58',
             'Rain': 'G6', 'Flow': 'G5', 'SOx': '10',
             'Temperature': '54',
             'Wind Speed': '51', 'Wind Direction': '52',
             'Hydrogen Chloride': '7', 'HF': '6', 'Pressure': '53',
             'TSS': 'G1', 'BOD': 'G3', 'COD': 'G2', 'TDS': 'G7',
             'Totalizer Flow': 'D1', 'CS2': 'D2', 'Opacity': 'D3',
             'VOC': 'D4',
             'Effluent (Temperature)': 'G4', 'CO2': '17',
             'Primay_Temp': 'D5',
             'Seconday_Temp': 'D6'}
